obj-$(CONFIG_CONNECTIVITY_HI1102) += hisi/
obj-$(CONFIG_CONNECTIVITY_HI11XX) += hi11xx/
subdir-ccflags-y += -Wno-typedef-redefinition -Wno-invalid-source-encoding \
-Wno-non-literal-null-conversion -Wno-enum-conversion -Wno-string-conversion